language: java
jdk:
- openjdk8
sudo: required
addons:
  ssh_known_hosts: 92.222.9.74
services:
- docker
branches:
  only:
  - dev
before_deploy:
- openssl aes-256-cbc -K $encrypted_17cdd5042447_key -iv $encrypted_17cdd5042447_iv -in deploy_key.enc -out /tmp/deploy_key -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_key
- ssh-add /tmp/deploy_key
install:
- docker-compose up -d
- mvn install
- sudo chmod -R 777 db_officeManager
deploy:
  provider: script
  skip_cleanup: true
  script: rsync -r --delete-after --quiet $TRAVIS_BUILD_DIR/ root@92.222.9.74:/deploy/officemanager-back
  on:
    branch: dev
after_deploy:
- ssh root@92.222.9.74 'chmod 777 /deploy/officemanager-back/script.sh'
- ssh root@92.222.9.74 '/deploy/officemanager-back/script.sh'
after_success:
- wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
- chmod +x send.sh
- "./send.sh success $WEBHOOK_URL"
after_failure:
- wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
- chmod +x send.sh
- "./send.sh failure $WEBHOOK_URL"



