language: java
jdk:
- openjdk8
sudo: required
addons:
  ssh_known_hosts: 51.178.82.205
services:
- docker
branches:
  only:
  - master
before_deploy:
- openssl aes-256-cbc -K $encrypted_17cdd5042447_key -iv $encrypted_17cdd5042447_iv -in deploy_key.enc -out /tmp/deploy_key -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_key
- ssh-add /tmp/deploy_key
install:
- mkdir db_officeManager
- chmod 777 -R db_officeManager
- docker-compose up -d --build
deploy:
  provider: script
  skip_cleanup: true
  script: rsync -r --delete-after --quiet $TRAVIS_BUILD_DIR/ root@51.178.82.205:/deploy/officemanager-back
  on:
    branch: master
after_deploy:
- ssh root@51.178.82.205 'chmod 777 /deploy/officemanager-back/script.sh'
- ssh root@51.178.82.205 '/deploy/officemanager-back/script.sh'
after_success:
- wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
- chmod +x send.sh
- "./send.sh success $WEBHOOK_URL"
after_failure:
- wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
- chmod +x send.sh
- "./send.sh failure $WEBHOOK_URL"

