version: '2'

services:
  #sonar:
  # image: sonarqube
  # ports:
  #      - 9000:9000
  db:
    image: mysql:8.0.2
    command: "--innodb_use_native_aio=0"
    container_name: office_manager_db
    environment:
      - MYSQL_DATABASE=officemanager   
      - MYSQL_USER=officemanager
      - MYSQL_PASSWORD=officemanager
      - MYSQL_ROOT_PASSWORD=officemanager
      - MYSQL_ROOT_HOST=%
    volumes:
      - ./db_officeManager:/var/lib/mysql
    restart: unless-stopped
    ports:
      - "3306:3306"
      - "33060"
    expose:
      - 3306
    networks:
      db_net:
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_ARBITRARY: 1
      MYSQL_USER: officemanager
      MYSQL_PASSWORD: officemanager
      MYSQL_ROOT_PASSWORD: officemanager
      #PMA_HOST: db
      #PMA_PORT: 3309
    ports:
      - "8808:80"
    networks:
      - db_net
     #links:
     #       # for mysql container
     #       - "db:db"
volumes: 
  db:
    driver: "local"
networks:
  db_net:
    driver: bridge

    
